### ISSUE TITLE
NullPointerException with Generic Deploy Task

### ISSUE THREAD

**Issue by asoftwareguy** [JFrogDev/bamboo-artifactory-plugin#11]
I am getting the following exception with plugin version 1.8.1 on Bamboo 5.9.3:
```
17-Aug-2015 11:10:27	Exception occurred while executing task
17-Aug-2015 11:10:27	java.lang.NullPointerException
17-Aug-2015 11:10:27	        at org.jfrog.bamboo.configuration.ConfigurationHelper.prepareRequestUrl(ConfigurationHelper.java:83)
17-Aug-2015 11:10:27	        at org.jfrog.bamboo.configuration.ConfigurationHelper.getAllVariables(ConfigurationHelper.java:56)
17-Aug-2015 11:10:27	        at org.jfrog.bamboo.builder.BaseBuildInfoHelper.filterAndGetGlobalVariables(BaseBuildInfoHelper.java:119)
17-Aug-2015 11:10:27	        at org.jfrog.bamboo.util.generic.GenericBuildInfoHelper.extractBuildInfo(GenericBuildInfoHelper.java:89)
17-Aug-2015 11:10:27	        at org.jfrog.bamboo.task.ArtifactoryGenericDeployTask.deploy(ArtifactoryGenericDeployTask.java:160)
17-Aug-2015 11:10:27	        at org.jfrog.bamboo.task.ArtifactoryGenericDeployTask.execute(ArtifactoryGenericDeployTask.java:90)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.task.TaskExecutorImpl$2.call(TaskExecutorImpl.java:278)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.task.TaskExecutorImpl$2.call(TaskExecutorImpl.java:274)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:200)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:274)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:110)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:75)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:196)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:124)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:115)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:215)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:114)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:118)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:49)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
17-Aug-2015 11:10:27	        at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
17-Aug-2015 11:10:27	        at java.lang.Thread.run(Thread.java:745)
```

**Comment by shikloshi** [comment]
Hi, 
Thanks for the report.
You can track this issue [here](https://www.jfrog.com/jira/browse/BAP-288) and also download a snapshot version containing the fix (be advised that it is not fully tested and contains only the fix for this issue).

Thanks,
Aviad.
