### ISSUE TITLE
Artifactory Maven 3 executable

### ISSUE THREAD

**Issue by fszilinski** [JFrogDev/bamboo-artifactory-plugin#29]
Hi,
in default AWS AMI Images for Bamboo Maven is available under "/opt/maven-3.3". According to "https://www.jfrog.com/jira/browse/BAP-171" the executable need to be setup by admin. I set "/opt/maven-3.3" for Artifactory Maven 3. In Tasks I get the following Exception.

Could it be that on ArtifactoryMaven3Task at line 227 the append("boot") is somehow wrong?
`       StringBuilder classPathBuilder = getPathBuilder(mavenHomePath).append("boot"); 
  `

Here the Exception:
`07-Jun-2016 13:06:46	Error occurred while running Task 'Build Project with Artifactory Maven(2)' of type org.jfrog.bamboo.bamboo-artifactory-plugin:maven3Task.
07-Jun-2016 13:06:46	java.lang.IllegalStateException: Could not find the Maven lib directory in the expected path: /opt/maven-3.3/boot.
07-Jun-2016 13:06:46	        at org.jfrog.bamboo.task.ArtifactoryMaven3Task.appendClassPathArguments(ArtifactoryMaven3Task.java:232)
07-Jun-2016 13:06:46	        at org.jfrog.bamboo.task.ArtifactoryMaven3Task.execute(ArtifactoryMaven3Task.java:112)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.task.TaskExecutorImpl.lambda$executeTasks$124(TaskExecutorImpl.java:269)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.task.TaskExecutorImpl.executeTaskWithPrePostActions(TaskExecutorImpl.java:202)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.task.TaskExecutorImpl.executeTasks(TaskExecutorImpl.java:269)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.task.TaskExecutorImpl.execute(TaskExecutorImpl.java:108)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.build.pipeline.tasks.ExecuteBuildTask.call(ExecuteBuildTask.java:74)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent.build(DefaultBuildAgent.java:215)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:139)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl$1.call(BuildAgentControllerImpl.java:130)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.variable.CustomVariableContextImpl.withVariableSubstitutor(CustomVariableContextImpl.java:215)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.v2.build.agent.BuildAgentControllerImpl.waitAndPerformBuild(BuildAgentControllerImpl.java:129)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.v2.build.agent.DefaultBuildAgent$1.run(DefaultBuildAgent.java:137)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.utils.BambooRunnables$1.run(BambooRunnables.java:49)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.security.ImpersonationHelper.runWith(ImpersonationHelper.java:31)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.security.ImpersonationHelper.runWithSystemAuthority(ImpersonationHelper.java:20)
07-Jun-2016 13:06:46	        at com.atlassian.bamboo.security.ImpersonationHelper$1.run(ImpersonationHelper.java:52)
07-Jun-2016 13:06:46	        at java.lang.Thread.run(Thread.java:745)`

StringBuilder classPathBuilder = getPathBuilder(mavenHomePath); //.append("boot");

**Comment by fszilinski** [comment]
Ok, it seems to work. Sorry about confusion. I added the executbale for Artifactory that pointed to "/opt/apache-maven-3.3.9". I misconfigured the path, I just set it for local Agents but I also had to set the executable for the AMI Instance image.
